name: mmtoolkit
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24
  - pandas>=2.1
  - matplotlib>=3.7
  - pip:
      - -e .
      - pyarrow>=14.0      # optional, remove if not needed
      #- ccxtpro>=2.0.0     # optional, remove if not needed
      - pytest>=8.2
      - pytest-asyncio>=0.23
      - black>=24.4
      - ruff>=0.5
      - pre-commit>=3.7