name: quanttradpublic
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - arrow-cpp=19.0.0
  - asttokens=2.4.1
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.2
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.528
  - blas=1.0
  - boost-cpp=1.78.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.15
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.11.0
  - debugpy=1.8.9
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fonttools=4.55.3
  - freetype=2.13.3
  - gflags=2.2.2
  - glog=0.5.0
  - icu=70.1
  - importlib-metadata=8.5.0
  - iniconfig=2.1.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.14.1
  - libcxx=19.1.4
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgrpc=1.71.0
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.5.2
  - orc=2.1.1
  - packaging=24.2
  - pandas=2.2.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=19.0.0
  - pygments=2.18.0
  - pyparsing=3.2.0
  - pytest=8.4.1
  - python=3.10.15
  - python-dateutil=2.9.0.post0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.1
  - pyzmq=26.2.0
  - re2=2024.07.02
  - readline=8.2
  - six=1.16.0
  - snappy=1.2.2
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.14
  - tomli=2.2.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - utf8proc=2.6.1
  - wcwidth=0.2.13
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - aiodns==3.2.0
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.10.11
    - aiosignal==1.3.1
    - async-timeout==5.0.1
    - attrs==24.2.0
    - backports-tarfile==1.2.0
    - ccxt==4.4.34
    - certifi==2024.8.30
    - cffi==1.17.1
    - charset-normalizer==3.4.0
    - cryptography==43.0.3
    - frozenlist==1.5.0
    - idna==3.10
    - jaraco-classes==3.4.0
    - jaraco-context==6.0.1
    - jaraco-functools==4.1.0
    - keyring==25.6.0
    - market-microstructure-toolkit==0.0.1
    - more-itertools==10.7.0
    - multidict==6.1.0
    - pip==25.2
    - propcache==0.2.0
    - pycares==4.5.0
    - pycparser==2.22
    - python-dotenv==1.1.0
    - requests==2.32.3
    - setuptools==80.9.0
    - urllib3==2.2.3
    - websockets==15.0.1
    - wheel==0.45.1
    - yarl==1.18.0
