name: quanttradpublic
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - comm=0.2.2
  - debugpy=1.8.9
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libcxx=19.1.4
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libsodium=1.0.20
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.10.15
  - python-dateutil=2.9.0.post0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.1
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024b
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
    - aiodns==3.2.0
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.10.11
    - aiosignal==1.3.1
    - async-timeout==5.0.1
    - attrs==24.2.0
    - backports-tarfile==1.2.0
    - ccxt==4.4.34
    - certifi==2024.8.30
    - cffi==1.17.1
    - charset-normalizer==3.4.0
    - cryptography==43.0.3
    - frozenlist==1.5.0
    - idna==3.10
    - jaraco-classes==3.4.0
    - jaraco-context==6.0.1
    - jaraco-functools==4.1.0
    - keyring==25.6.0
    - more-itertools==10.7.0
    - multidict==6.1.0
    - propcache==0.2.0
    - pycares==4.5.0
    - pycparser==2.22
    - python-dotenv==1.1.0
    - requests==2.32.3
    - urllib3==2.2.3
    - websockets==15.0.1
    - yarl==1.18.0
