[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "market_microstructure_toolkit"
version = "0.0.1"
description = "Research toolkit for order book microstructure"
authors = [{name="Leonardo Placidi"}]
requires-python = ">=3.9"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]