name: CI

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:

jobs:
  test:
    name: test (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    env:
      # Make the test suite write logs where tests expect them
      MMT_LOG_DIR: tests/_artifacts/logs
      # Headless plotting for matplotlib
      MPLBACKEND: Agg
      # Avoid locale/encoding flakiness
      PYTHONUTF8: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Show Python & pip
        run: |
          python -V
          pip -V

      - name: Prepare test artifact directories
        run: |
          mkdir -p tests/_artifacts/logs
          mkdir -p tests/_artifacts

      - name: Install package + dev tools
        run: |
          python -m pip install --upgrade pip
          # Install your package with dev extras if available; otherwise fall back to explicit tools
          pip install -e .[dev] || pip install -e . pre-commit pytest ruff black
          # Optional runtime deps used by tests/CLIs
          pip install pyarrow ccxt
          # DO NOT install ccxtpro on CI

      - name: Lint (pre-commit)
        uses: pre-commit/action@v3.0.1

      - name: Run tests
        run: |
          pytest -q --maxfail=1 -ra

      - name: Upload logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs-${{ matrix.python-version }}
          path: tests/_artifacts/logs/*
          if-no-files-found: ignore

  build:
    name: build
    if: github.ref_type == 'tag' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Build wheels/sdist
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    name: publish
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write     # for PyPI Trusted Publishing
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          # If not using Trusted Publishing, add:
          # password: ${{ secrets.PYPI_API_TOKEN }}